applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: <https://github.com/Sfilosha/my-microservice-project/tree/lesson-8>
      path: django-chart
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: <https://kubernetes.default.svc>
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
repositories:
  - name: app
    url: <https://github.com/Sfilosha/my-microservice-project/tree/lesson-8>
    type: git
    secretRef:
      name: repo-secret


repoConfig:
  insecure: "true"
  enableLfs: "true"
